name: Push App To gh-pages Branch

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      
      - name: Gets The Repository Code
        uses: actions/checkout@v3

      - name: add commit and push workflow and app to gh-pages
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git branch gh-pages
          git add .github/workflows/githubpages.yaml
          git add app
          git commit -m "Added Worflow and App to gh-pages"
          git push -u origin gh-pages

      # - name: Push App To gh-pages
      #   uses: s0/git-publish-subdir-action@develop
      #   env:
      #     REPO: self
      #     BRANCH: gh-pages
      #     FOLDER: ./app 
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     MESSAGE: "Move App To gh-pagess: ({sha}) {msg}"

      # - name: Push workflow To gh-pages
      #   uses: s0/git-publish-subdir-action@develop
      #   env:
      #     REPO: self
      #     BRANCH: gh-pages
      #     FOLDER: .github 
      #     TARGET_DIR: .github
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     MESSAGE: "Move App To gh-pagess: ({sha}) {msg}"
