
name: Build For Github Pages

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      
      - name: Gets The Repository Code
        uses: actions/checkout@v3
      
      - name: Setup Node V ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean Install
        run: npm ci

      - name: Add .nojekyll
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "public/.nojekyll"
          FILE_DATA: " "

      - name: Build The App
        run: npm run build --if-present

      - name: Push To gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./app/dist 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
